[tool.poetry]
name = "moon"
version = "0.1.0"
description = ""
authors = ["Patrick Tarnaud <patrick.tarnaud@mail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
PySide6 = "^6.1.2"
Babel = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
